/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#10141a",
        "deep-space": "#0d1117",
        abyss: "#000000",
        carbon: "#090d0a",
        obsidian: "#151a22",
        surface: "#181c22",
        "surface-container": "#1c2026",
        "surface-container-low": "#181c22",
        "surface-container-high": "#262a31",
        "surface-container-highest": "#31353c",
        "surface-high": "#262a31",
        "slate-edge": "#21262d",
        iron: "#3d4145",
        fog: "#484f58",
        moss: "#7c8980",
        mercury: "#818b98",
        ash: "#9ea0a2",
        pearl: "#a4aea6",
        "on-surface": "#dfe2eb",
        snow: "#ffffff",
        "terminal-green": "#08872b",
        "primary-container": "#08872b",
        phosphor: "#5fed83",
        primary: "#70dd75",
        secondary: "#86cff8",
        tertiary: "#bfc2ff",
        "tertiary-container": "#636acf",
        violet: "#8c93fb",
        sky: "#8dd6ff",
        error: "#ffb4ab",
        "error-container": "#93000a",
        danger: "#ffb4ab",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "monospace"],
      },
      fontSize: {
        "label-mono": ["12px", { lineHeight: "1.5", letterSpacing: "0.015em", fontWeight: "500" }],
        caption: ["12px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.5", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.5", fontWeight: "440" }],
        "headline-md": ["40px", { lineHeight: "1.2", fontWeight: "460" }],
        "headline-lg": ["48px", { lineHeight: "1.0", letterSpacing: "-0.02em", fontWeight: "460" }],
        "display-xl": ["64px", { lineHeight: "1.08", letterSpacing: "-0.035em", fontWeight: "425" }],
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        gutter: "24px",
        md: "24px",
        lg: "48px",
        xl: "80px",
      },
      maxWidth: {
        page: "1200px",
        "max-width": "1200px",
      },
      borderRadius: {
        card: "24px",
        panel: "16px",
        control: "6px",
        pill: "9999px",
      },
    },
  },
  plugins: [],
};
